version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.7
    commands:
      - aws cloudformation package --template-file server/samTemplate.yaml --s3-bucket dr11-prashanth --output-template-file server/outputTemplate.yaml
artifacts:
  type: zip
  files:
    - server/samTemplate.yaml
    - server/outputTemplate.yaml